FROM nvidia/cuda:11.6.2-cudnn8-runtime-ubuntu20.04

COPY . /onnx-olive
WORKDIR /onnx-olive

RUN python -m pip install --upgrade pip
RUN pip install onnxruntime-gpu==1.12.1
RUN pip install mlperf_loadgen --extra-index-url https://olivewheels.azureedge.net/test
RUN pip install -e .

CMD ["bash"]
